### ISSUE TITLE
Move blog forum ID constant to config.php

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#100]
Right now, the constant is defined here:
https://github.com/OPSnet/Gazelle/blob/d9920427fd09c37434a2a6634baf3dbb16339f85/sections/blog/index.php#L4

This should be moved within config.php. This forum constant can also be used for #99.

**Comment by itismadness** [comment]
Yeah, this should also be moved into config.php, and given it's own constant name separate from the normal blog and announcement constant. Good catch.

**Comment by oieeq** [comment]
Looks like it's defined in the staffblog, but not actually being used for staffblog posts?
