### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alby696** [OPSnet/Gazelle#107]
Hi everyone,
I tried to install everything via the file gazelle-setup.sh on debian 9 but also on ubuntu manually, following all the steps correctly.
In the end, when it has to restart all the services, it gives me error in PHP and in FASTCGI.
I tried not to make him copy the php.ini file but the probelma persists.
Can someone help me?
Thank you
alby696

**Comment by andrey1103** [comment]
Some details about the errors....

**Comment by alby696** [comment]
Hi,
the error that I generate php7.0 is this.
Thanks
![schermata 2019-02-27 alle 08 35 38](https://user-images.githubusercontent.com/15062741/53473641-39f85b00-3a6b-11e9-9a80-a8d94269fc9e.png)
![schermata 2019-02-27 alle 08 38 09](https://user-images.githubusercontent.com/15062741/53473642-39f85b00-3a6b-11e9-802c-dd1a99d0a4a3.png)

**Comment by andrey1103** [comment]
You need to edit 
nano /etc/php/7.0/fpm/pool.d/www.conf
Change:
user = vagrant
group = vagrant
With:
user = www-data
group = www-data

And start php again
service php7.0-fpm start
