### ISSUE TITLE
Default admin password?

### ISSUE THREAD

**Issue by KamillaPup** [OPSnet/Gazelle#111]
What password is used for the admin account? Do I even need to use it to sign in? I was going to reset it in phpmyadmin but noticed that it doesn't use MD5 hashing (which is good). It probably uses a custom salt configured in config.php?

**Comment by KamillaPup** [comment]
Or is my account SysOp? INSTALL.txt in docs states the first account made has full permissions, but I'm not sure that's the case.

**Comment by andrey1103** [comment]
https://github.com/OPSnet/Gazelle/blob/master/db/seeds/InitialUserSeeder.php

**Comment by itismadness** [comment]
When you first install Gazelle, you should enable registration that first user will be automatically made SysOp as well as not having to validate their registration.

I would not suggest using the InitialUserSeeder as that's more aimed for Vagrant usage.

If you wanted to reset the password, you'd want to use [password_hash](http://php.net/manual/en/function.password-hash.php) to generate a new hashed password that you'd then save into the DB.
