### ISSUE TITLE
IRC Issue

### ISSUE THREAD

**Issue by muyu1232** [OPSnet/Gazelle#116]
If I want to enable IRC services, I just need to setting config.php Or  need to install Hermes after setting config.php

**Comment by itismadness** [comment]
The instructions are somewhat muddled as originally, it appears as if WhatCD had built their IRC bot directly into the PHP code of the site, but refactored it out into a standalone thing at some point.

To get this to work, you'll want to configure:
```
define('SOCKET_LISTEN_PORT', 51010);
define('SOCKET_LISTEN_ADDRESS', 'localhost');
```
to point to wherever you have [hermes](https://github.com/OPSnet/hermes) (or some alternative IRC bot) running. You'll then want to configure the various `*_CHAN` to fit your needs, though I believe `#announce` channel name is hard-coded in gazelle at the moment.
