### ISSUE TITLE
Remove classes/zip.class.php

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#13]
The [classes/zip.class.php](https://github.com/OPSnet/Gazelle/blob/aa71218e85421aa6d0d7faf45038ab3c98456201/classes/zip.class.php) was written back before Gazelle was using PHP 5 and it was necessary. However, it now basically just mimics the builtin [Zip](http://php.net/manual/en/book.zip.php) class which we should switch to using instead.

**Comment by Empornium** [comment]
Have a look at https://github.com/maennchen/ZipStream-PHP

We used this to allow the creation of arbitrarily large zip files without exhausting memory on the server.
