### ISSUE TITLE
looped redirection when user want disable 2fa

### ISSUE THREAD

**Issue by soleil0-0** [OPSnet/Gazelle#133]
https://github.com/OPSnet/Gazelle/blob/0b7ed1c4666fb57c736eb17238ea0f1b4628cd8d/sections/user/index.php#L156

Users without 'users_edit_password' permission but with 'users_mod' permission will encounter looped redirection when they want disable 2fa.

**Comment by ops-webhead** [comment]
Thanks for reporting this. I've submitted a possible fix and will let you know when it's done.

**Comment by itismadness** [comment]
Fixed in 62014bb3ca88b5c654582c9adc7799c1ab838444.
