### ISSUE TITLE
Install Guide?

### ISSUE THREAD

**Issue by ModernAesthetics** [OPSnet/Gazelle#138]
I would really love if we could get a full install guide to get up and running.

**Comment by itismadness** [comment]
We provide https://github.com/OPSnet/Gazelle/blob/master/docs/INSTALL.txt as well as have a docker-compose setup that puts all minimum pieces into place to run Gazelle / Ocelot. Someone sufficiently technical should be able to piece together what needs doing from there for now.

We're happy to accept PRs to add more details and cover more advanced topics and such, but it's not a priority of ours compared to all the various bugs, suggestions, and just general code improvements we are working on.
