### ISSUE TITLE
Integrate bencode-torrent library into Gazelle

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#14]
Right now, Gazelle has the following classes:
* [bencode.class.php](https://github.com/OPSnet/Gazelle/blob/aa71218e85421aa6d0d7faf45038ab3c98456201/classes/bencode.class.php)
* [bencodedecode.class.php](https://github.com/OPSnet/Gazelle/blob/aa71218e85421aa6d0d7faf45038ab3c98456201/classes/bencodedecode.class.php)
* [bencodetorrent.class.php](https://github.com/OPSnet/Gazelle/blob/aa71218e85421aa6d0d7faf45038ab3c98456201/classes/bencodetorrent.class.php)
* [torrent_32bit.class.php](https://github.com/OPSnet/Gazelle/blob/master/classes/torrent_32bit.class.php) / [torrent.class.php](https://github.com/OPSnet/Gazelle/blob/aa71218e85421aa6d0d7faf45038ab3c98456201/classes/torrent.class.php)

This should all be replaced with usage of https://github.com/OPSnet/bencode-torrent which is preferable as it's (a) tested and (b) a single implementation instead of the several Gazelle has.

**Comment by garrettw** [comment]
The first three files can be easily replaced by the external lib, but the latter one not so much being that it's the legacy implementation anyway. So I'm about to make a PR to address the first three.
