### ISSUE TITLE
Still waiting for Web, NOT FUNCTION on ubuntu 18.04

### ISSUE THREAD

**Issue by Serialc0de** [OPSnet/Gazelle#140]
NOT function brò, server clear install docker ubuntu 18.04

![gg](https://user-images.githubusercontent.com/40340347/102688328-6eb44400-41f6-11eb-82d6-e36f1d414cad.PNG)

there is no installation guide, we are not all professionals like you unfortunately!

**Comment by ops-webhead** [comment]
Looks like composer didn't install. Were there any errors before this?

**Comment by R3D4CTED** [comment]
Same, except I got:
`PHINX FAILED TO SEED`

Error was:
```
In PdoAdapter.php line 339:
web_1           |
web_1           |   SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'n
web_1           |   ow()' for column `gazelle`.`user_last_access`.`last_access` at row 1
web_1           |
web_1           |
web_1           | seed:run [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-s|--seed SEED]
```

**Comment by itismadness** [comment]
The SQL error that phinx is failing to seed is different from the above error where it looks like composer failed to install stuff.

We haven't seen this error yet over the last 8 months, so closing for now. Feel free to open a new issue if still hitting this error.
