### ISSUE TITLE
WEB fails to start on Ubuntu 20.04

### ISSUE THREAD

**Issue by R3D4CTED** [OPSnet/Gazelle#141]
```
Run seed:run...
web_1           | Phinx by CakePHP - https://phinx.org.
web_1           |
web_1           | using config file ./phinx.php
web_1           | using config parser php
web_1           | using migration paths
web_1           |  - /var/www/db/migrations
web_1           | using seed paths
web_1           |  - /var/www/db/seeds
web_1           | warning no environment specified, defaulting to: gazelle
web_1           | using adapter mysql
web_1           | using database gazelle
web_1           |
web_1           |  == InitialUserSeeder: seeding
web_1           |
web_1           | In PdoAdapter.php line 339:
web_1           |
web_1           |   SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'n
web_1           |   ow()' for column `gazelle`.`user_last_access`.`last_access` at row 1
web_1           |
web_1           |
web_1           | seed:run [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-s|--seed SEED]
web_1           |
web_1           | PHINX FAILED TO SEED
gazelle_web_1 exited with code 1
```
Running it on Docker Desktop (Windows) through WSL(Ubuntu 20.04). Everything else (Memcached, MariaDB) seems to have built and are running fine. SphinxSearch is still waiting for web to start.

Steps taken to reproduce:
* Run Docker Desktop on Windows
* Open WSL, clone git repository to a folder and run `docker-compose up` and it sets everything up, but fails at that step even when restarted. Any configs that need to be set/changed?

**Comment by R3D4CTED** [comment]
UPDATE: Tried it on Ubuntu 20.04 VM and it worked flawlessly.

**Comment by itismadness** [comment]
Not really sure what would be causing it to fail, as docker should be giving us a consistent environment across platforms. This issue may also have been resolved in our latest code update, not sure. Tested that `docker-compose up` worked in WSL, macOS, and Ubuntu.
