### ISSUE TITLE
docker-compose fails because vendor directory cannot be created.

### ISSUE THREAD

**Issue by alexohneander** [OPSnet/Gazelle#176]
I can't run the docker-compose because the phinx migration can't be executed. I think it is because the vendor directory cannot be created. I already tried to create in the docker file a mkdir but unfortunately, that didn't help.

```
web_1           |   [RuntimeException]
web_1           |   /var/www/vendor does not exist and could not be created.
```

```
web_1           | Run migrations...
web_1           | /var/www/.docker/web/entrypoint.sh: line 33: /var/www/vendor/bin/phinx: No such file or directory
web_1           | PHINX FAILED TO RUN MIGRATIONS
```

**Comment by alexohneander** [comment]
If you create the directory before the build, it works.
Would it make sense to create the empty directory in Git?

**Comment by 112RG** [comment]
Are you running it as root? If so that is most likely the problem
