### ISSUE TITLE
Docker Image pointing at invalid ocelot image...

### ISSUE THREAD

**Issue by mcangeli** [OPSnet/Gazelle#210]
When running the docker compose up for the gazelle docker, it errors out on the ocelot package.

`
WARNING: Image for service sphinxsearch was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling ocelot (ocelot:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling ocelot (ocelot:)...
ERROR: pull access denied for ocelot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
admin@ip-172-31-17-250:/var/www/dev/Gazelle$
`

**Comment by itismadness** [comment]
Yeah, previously you had to build ocelot from https://github.com/OPSnet/Ocelot before running this repo. This has been changed so now can use the repo as is, and there's a secondary `docker-compose.yml` file to run ocelot in conjunction. See https://github.com/OPSnet/Gazelle#ocelot for details on that.
