### ISSUE TITLE
Migration cannot proceed

### ISSUE THREAD

**Issue by blobb3r** [OPSnet/Gazelle#214]
I'm just looking around and want to improve my skills - so don't bash to hard please. 

Got some errors and managed to fix them all, but now im not sure what to do with this one:
Migration cannot proceed, use the source: /var/www/misc/phinx/migrations/20200219075508_drop_secret.php

Some migration parts are going through fine but this one isn't. Anyone know why?

**Comment by blobb3r** [comment]
Actually 'solved' it by commenting that if statement out that's causing this. It appears it has something to do with and security env variable which is not set..?

**Comment by itismadness** [comment]
When running the migrations directly, will need to set the `FKEY_MY_DATABASE` and `LOCK_MY_DATABASE` environment variables as running them on a full production site that's live causes severe issues, and better to first take the site offline or run the migration stuff manually.

See the comments on:
* https://github.com/OPSnet/Gazelle/blob/474eebe29da9c9703a6a972ec627052f78ec2d8c/misc/phinx/migrations/20200219075508_drop_secret.php
* https://github.com/OPSnet/Gazelle/blob/474eebe29da9c9703a6a972ec627052f78ec2d8c/misc/phinx/migrations/20200427085116_index_refactor.php#L29

for more info
