### ISSUE TITLE
Replace calls to Google Charts with internal usage of D3

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#22]
Example is the `/stats.php?action=users` endpoint

**Comment by Empornium** [comment]
I've looked at this previously, would be very interested to implementation and may even "borrow" it. ;-)

**Comment by itismadness** [comment]
This was done in a couple steps, and we now use [highcharts](https://github.com/highcharts/highcharts) for our chart generation.

The relevant commits are:
36bdd61d523bd905a0449ac51839180c692ef18b (apologies this is a dump of a lot of unrelated stuff)
4f11e8e595dadc324ad035fd5b0998e59fdf1470
