### ISSUE TITLE
installing problem

### ISSUE THREAD

**Issue by xrTor** [OPSnet/Gazelle#3]
i got this problem
http://localhost:8080/
```
MySQL: Invalid Query: 
				SELECT ID, Name, Level, Secondary
				FROM permissions
				ORDER BY Level SQL error: 1146 (Table 'gazelle.permissions' doesn't exist)
Array ( [0] => Array ( [0] => SELECT ID, Name, Level, Secondary FROM permissions ORDER BY Level [1] => 0.080108642578125 [2] => ) )
```

installed vagrant with virtual machine on windows

also how i connecting to phpmyadmin?

**Comment by ligh7s** [comment]
Did you ever initialize the tables in the DB? Schema/script found here: https://github.com/ApolloRIP/Gazelle/blob/master/db/data/gazelle.sql  

I don't know why you're linking to localhost, since we aren't in your network.

**Comment by itismadness** [comment]
As @ligh7s said, it looks like you haven't setup the database. I suggest using [Phinx](https://phinx.org) to do this for you.

**Comment by itismadness** [comment]
Closing as stale.
