### ISSUE TITLE
Set the download location for the GeoIP database to location of sys_get_temp_dir

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#42]
Gazelle tries to download the GeoIP database in place of where it's being executed. It should try and download it to the location of wherever [sys_get_temp_dir](http://php.net/manual/en/function.sys-get-temp-dir.php) points to.

**Comment by SebbaGerra** [comment]
GeoIP database no longer works

**Comment by itismadness** [comment]
Removed in be1e3f67981615f7156ef1633194846b0f4e4ca7 due to change in licensing on the GeoIP database we were relying on. We do not have plans to bring this feature back.
