### ISSUE TITLE
Don't allow users to go past the results page of SphinxSearch

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#53]
Sphinx will only return so many results as configured by the `SPHINX_MAX_MATCHES` variable. However, Gazelle will happily let you keep going based on the absolute number of matches in the DB. This creates a jarring interaction for the user. 

The user should not be allowed to scroll past the end point, and Gazelle should output a message saying "The first `SPHINX_MAX_MATCHES` matches are shown." or something to alert users there are more matches than will be shown.

**Comment by ligh7s** [comment]
https://github.com/OPSnet/Gazelle/pull/57
