### ISSUE TITLE
Use wiki aliases for key wiki article links

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#68]
Right now, a lot of the wiki articles around the site point to a specific ID. That means that in addition to having to make the articles, we need to also make a commit to update the ID that these links point to. It would be far easier going forward to just have them point to an alias instead so that even if the article IDs were ever changed, the site itself would not break (assuming the articles still exist).

An example is the wiki link for warnings.

**Comment by ops-webhead** [comment]
Can be closed
