### ISSUE TITLE
Make sure all array accesses are quoted

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#74]
In far too many places, Gazelle does not use quote around the string key within an array, such as here:
https://github.com/OPSnet/Gazelle/blob/9626636c921f73c6f7f0133612feb34d2355882c/sections/requests/requests.php#L62
This will emit an E_WARNING in PHP 7.2 (http://php.net/manual/en/migration72.deprecated.php#migration72.deprecated.unquoted-strings) and should be fixed.

**Comment by HDVinnie** [comment]
Correct me if I'm wrong but with your example it would be best converted to the following?
`$Title = "Requests created by {$UserInfo['Username']}";`

**Comment by itismadness** [comment]
Yup, that is how you would fix that particular example.

Fixed though in 85118e8ae7338897aeb103c16a6cce7b61594eb2. Any remaining stragglers will get cleaned up subsequently due to merge conflicts or whatever internally.
