### ISSUE TITLE
Save HTTP_USER_AGENT to users_sessions table if browser changes in session

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#78]
Some users are using an identification string that WhichBrowser cannot parse. It would help if we record these so that we can look into either making upstream patches or at least understand that they're nonsense.

**Comment by a205494** [comment]
Aren't we doing this? The FullUA column?

**Comment by itismadness** [comment]
Looking into this further, Gazelle sort of does this. So it saves the full user agent when a user initially logs in. However, if a user then switches browser or operating system, it'll save the values for that when updating the session, but not the new user agent. So I'd like to fix that it's not updating the user agent when just browsing the site.
