### ISSUE TITLE
PHP warning when browsing torrent page

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#83]
Code | Warning | Line
------|---------|-----
include() | Undefined variable: Left | /sections/torrents/browse.php:144

(should test both when showing album art and not)

**Comment by oieeq** [comment]
Uncommenting these lines removes this warning, but may be introducing other issues? I assume they are commented out for a reason.

https://github.com/OPSnet/Gazelle/blob/d9920427fd09c37434a2a6634baf3dbb16339f85/sections/torrents/browse.php#L138-L141

**Comment by ThePadawan** [comment]
The affected code seemingly no longer exists (https://github.com/OPSnet/Gazelle/blob/327dbca8b57a59411c9effb07d1cb4fe00ef125d/sections/torrents/browse.php#L1).

Can this issue be resolved?
