### ISSUE TITLE
Display 2FA code as copyable text under QR code

### ISSUE THREAD

**Issue by itismadness** [OPSnet/Gazelle#84]
Right now, the QR code is generated and a non-copyable text string is displayed underneath it. There's no point having this text in an image as it doesn't really make things more secure, and some members use services where they must enter the text into their application. We should just display this text string as a normal, copyable text string.

**Comment by a205494** [comment]
https://github.com/OPSnet/Gazelle/pull/92 Simple fix

**Comment by itismadness** [comment]
Done in #92 / e6aa51d36c5607e8a31b81950925e83e8f8d5a16.
