### ISSUE TITLE
Some db tables doesn't exist in gazelle.sql

### ISSUE THREAD

**Issue by haffax7** [OPSnet/Gazelle#93]
some db tables doesn't exist in gazelle.sql

`bonus_item`
applicant
`featured_albums` ADD `Type` 
`users_sessions` ADD `BrowserVersion`
`users_sessions` ADD `OperatingSystemVersion`
`users_info` ADD `NotifyOnDeleteSeeding`
`users_info` ADD `NotifyOnDeleteSnatched`
`users_info` ADD `NotifyOnDeleteDownloaded`

and some more.

Please update the gazelle.sql file.
Thanks

**Comment by bifrosty** [comment]
These are all in db/migrations. Run phinx migrate in vendor/bin.

**Comment by haffax7** [comment]
Oh Thanks!  👍
